/**
 * GNU BIN TOOLS
 * 
 * SUITE OF TOOLS THAT COME WITH 
 * INSTALLATION OF THE GNU TOOLCHAIN 
 * FOR ARM
 * 
 * ARM-NONE-EABI-GCC COMPONENTS
 * 
 *      ARM: TARGET ARCHITECTURE
 *      NONE: OS FOR WHICH THE CODE IS COMPILED
 *      EABI: EMBEDDED APPLICATION BINARY INTERFACE
 *      IT DEFINES STANDARD FOR THE BIN LAYOUT OF SYSTEM
 *      AND USER PROGRAMS
 *      GCC: GNU COMPILER COLLECTION
 *      
 */