/**
 * EMBEDDED FIRMWARE BUILD PROCESS
 * 
 * GOAL:
 *      - EMBEDDED BUILD PROCESS
 *      - GNU BINARY TOOLS
 *      - IDE TO CLI
 * 
 * BUILD PROCESS
 *      - INTRICATE AND MULTILAYERED
 *      1. SOURCE FILES
 *      2. PREPROCESSOR
 *      3. PREPROCESSED FILES
 *      4. COMPILER
 *      5. ASSEMBLY FILES
 *      6. ASSEMBLER
 *      7. OBJECT FILES
 *      8. LINKER
 *      9. RELOCATABLE FILE
 *      10. LOCATOR
 *      11. EXECUTABLE
 * 
 * PREPROCESSING STAGE
 *      1. COMMENTS REMOVED FROM CODE
 *      2. REPLACE # TO CODE SEGMENTS
 *      3. OUTPUT .i FILE
 * 
 * COMPILATION STAGE
 *      1. PROCESS .i FILES
 *      2. OUPUT ASSEMBLY CODE FILES (.s)
 * 
 * ASSEMBLY STAGE
 *      1. PROCESS .s FILES 
 *      2. CONVERTS TO MACHINE CODE
 *      3. OUTPUT .o FILES
 *      * they contain binary
 * 
 * LINKING STAGE
 *      1. STITCHES ALL .o FILES
 *      2. GENERATES RELOCATABLE FILE
 */