/**
 * SOME COMMON COMPILER FLAGS
 * 
 *      -c: COMPILE AND ASSEMBLE BUT NOT LINK
 *      -o: NAME OF THE OUTPUT FILE
 *      -g: GENERATES DEBUGGING INFO
 *      -Wall: ENABLES ALL WARNING MESSAGES
 *      -Werror: TREATS ALL WARNINGS AS ERRORS
 *      -I: SPECIFIC DIRECTORY TO SEARCH FOR HEADER FILES
 *      -ansi and -std=STANDARD: SPECIFY VERSION OF C LANG TO BE USED
 *      -v: VERBOSE OUTPUT FROM FCC
 *
 * ARCHITECTURE-SPECIFIC FLAGS
 * 
 *      -mcpu: SPECIFIES TARGET ARM PROCESSOR
 *      -march: SPECIFIES THE TARGET ARM ARCHITECTURE
 *      -mtune: OPTIMIZATION BY TARGETING ARM PROCESSOR
 *      -thumb: CONFIGURES THE COMPILER TO GENERATE CODE FOR THUMB
 *      INSTRUCTION SET
 *      -marm: INSTRUCTS THE COMPILER TO GENERATE CODE
 *      FOR ARM INSTRUCTION SET
 *      -mlittle-endian/-mbig-endian: SPECIFY ENDIANNESS 
 *      FOR THE GENERATED CODE. LITTLE-ENDIAN IS MOST COMMON
 *      IN ARM
 * 
 * EXAMPLE
 * 
 *      `arm-none-eabi-gcc -c -mcpu=cortex-m4 -thumb main.c -o main.o`
 *      
 */