/**
 * Understanding STM32 MEMORY MODEL
 * 
 * SRAM
 * READ AND WRITE: VARIABLES AND THE STACK ARE STORED
 * MEMORY START AT 0X20000000
 * VARIABLE SIZE
 * 
 * 
 * FLASH MEMORY
 * - NOT LOST AFTER POWER DISCONNECT
 * - PRIMARILY USED FOR STORING PROGRAM CODE
 * STARTS AT 0X08000000
 * VECTOR TABLE LOCATION: 0X08000004
 * 
 * 
 * 
 */