/**
 * LINKER SCRIPT
 * 
 * PLAYS A ROLE IN THE BUILD PROCESS
 * 
 * SPECIFY WHERE DIFFERENT SECTIONS OF THE FIRMWARE, SUCH AS CODE, DATA, AND UNINITIALIZED DATA
 * ARE TO BE PLACED IN THE MICROCONTROLLER'S MEMORY.
 * 
 * 
 */